In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline
df = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv") #これはモデル学習のための？SalePriceないけどどうやって使うん？
df

MSSubClass  Neighborhood  OverallQual  YearBuilt  YearRemodAdd  \
0           14.0          16.0          6.0       96.0          42.0   
1           11.0          20.0          5.0       70.0          31.0   
2           14.0          16.0          6.0       99.0          53.0   
3            9.0          17.0          6.0       31.0          16.0   
4           14.0          24.0          7.0       87.0          38.0   
5            6.0          11.0          4.0       90.0          47.0   
6           11.0          19.0          7.0       85.0          50.0   
7           14.0          13.0          6.0       40.0          15.0   
8            6.0           5.0          6.0       21.0           1.0   
9            3.0           3.0          4.0       53.0           1.0   
10          11.0           6.0          4.0       55.0          18.0   
11          14.0          23.0          8.0       97.0          57.0   
12          11.0           6.0          4.0       50.0          20.0   
13          11.0          16.0          6.0      102.0          56.0   
14          11.0          10.0          5.0       66.0          19.0   
15           2.0           3.0          6.0       54.0          41.0   
16          11.0          10.0          5.0       33.0          16.0   
17           4.0           6.0          3.0       47.0          10.0   
18          11.0          12.0          4.0       85.0          43.0   
19          11.0          10.0          4.0       48.0          18.0   
20          14.0          23.0          7.0       97.0          57.0   
21           2.0           1.0          6.0        3.0           1.0   
22          11.0          16.0          7.0       95.0          53.0   
23          13.0           0.0          4.0       70.0          31.0   
24          11.0           6.0          4.0       73.0          41.0   
25          11.0          23.0          7.0      103.0          56.0   
26          11.0          10.0          4.0       37.0          38.0   
27          11.0          23.0          7.0      103.0          58.0   
28          11.0          10.0          4.0       52.0          52.0   
29           0.0           3.0          3.0        0.0           1.0   
...          ...           ...          ...        ...           ...   
1430        14.0          14.0          4.0       97.0          50.0   
1431        13.0           9.0          5.0       70.0          31.0   
1432         0.0           5.0          3.0        0.0          56.0   
1433        14.0          14.0          5.0       87.0          38.0   
1434        11.0          11.0          4.0       74.0          28.0   
1435        11.0          10.0          5.0       50.0          50.0   
1436        11.0          10.0          3.0       26.0           2.0   
1437        11.0          23.0          7.0      110.0          58.0   
1438        11.0           5.0          5.0       52.0          51.0   
1439        14.0          13.0          6.0       58.0          23.0   
1440         9.0          17.0          5.0        7.0          54.0   
1441        13.0          16.0          5.0       85.0          43.0   
1442        14.0          19.0          9.0      110.0          58.0   
1443         0.0           3.0          5.0       42.0           1.0   
1444        11.0          16.0          6.0       85.0          43.0   
1445         7.0           6.0          5.0       62.0          22.0   
1446        11.0          11.0          4.0       50.0          20.0   
1447        14.0          16.0          7.0      105.0          51.0   
1448         6.0           4.0          3.0       11.0          38.0   
1449         1.0           0.0          4.0       33.0          16.0   
1450         4.0          10.0          4.0       78.0          30.0   
1451        11.0          19.0          7.0      110.0          59.0   
1452         1.0           4.0          4.0       97.0          50.0   
1453        11.0          11.0          4.0   

In [3]:
# DataFrameの.valuesメソッドでarrayに変換、ヒートマップから選んだ相関係数の高いやつらを抽出。
X = df.loc[:, ['Neighborhood', 'OverallQual', 'ExterQual', 'GrLivArea', 'KitchenQual',
       'GarageCars']].values
X_all = df.loc[:,['1stFlrSF', 'BsmtQual', 'ExterQual', 'Fireplaces', 'Foundation',
       'FullBath', 'GarageArea', 'GarageCars', 'GarageFinish',
       'GarageType', 'GarageYrBlt', 'GrLivArea', 'HeatingQC',
       'KitchenQual', 'MSSubClass', 'MasVnrArea', 'MasVnrType',
       'Neighborhood', 'OverallQual', 'TotRmsAbvGrd',
       'TotalBsmtSF', 'YearBuilt', 'YearRemodAdd']].values
# DataFrameの.valuesメソッドでarrayに変換
y = df.loc[:, ['SalePrice']].values

In [4]:
# ホールド・アウト法によるデータの分割
# (X, y, テストにどの割合を割くか, 分割のしかたを決める乱数生成器)
# テストデータの割合は、test_size引数に指定することで変更可能です（今回は、train:test = 7:3）
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [5]:
# データ全体のサンプル数を確認
print(X.shape)
print(y.shape)
# trainデータのサンプル数を確認
print(X_train.shape)
print(y_train.shape)
# 重回帰の線形回帰を実行
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
# 重回帰線形モデルの学習
# trainデータのみを用いていることに注意
lr.fit(X_train, y_train)

(1460, 6)
(1460, 1)
(1022, 6)
(1022, 1)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [6]:
# 定数項を出力
lr.intercept_

array([-52331.27326364])

In [7]:
# 偏回帰係数を出力
lr.coef_

array([[  2511.63037829,  12420.10795364,  10399.98233689,     53.721416  ,
         13235.08713712,  12667.69981218]])

In [8]:
# 自由度調整済み決定係数
# (決定係数, trainまたはtestのサンプル数, 利用した特徴量の数)
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score
# 自由度調整済み決定係数を出力
print('adjusted R^2')
print('train: %3f' % adjusted(lr.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(lr.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.803839
test : 0.769353


In [9]:
# MSEを出力する関数を読み込む
from sklearn.metrics import mean_squared_error as mse
# RMSEをtrainとtestに分けて出力
# 過学習をしているかどうかを確認
print('RMSE')
print('train: %.3f' % (mse(y_train, lr.predict(X_train)) ** 1/2))
print('test : %.3f' % (mse(y_test, lr.predict(X_test)) ** 1/2))

RMSE
train: 597096009.202
test : 779348170.834


In [10]:
#RMSEが意味わかんない位大きいので,全部の説明変数ぶっこんで標準化して見落としてる変数がないか確かめてみる。
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_std = ss.fit_transform(X_all)
y_std = ss.fit_transform(y)

In [11]:
X_std.mean()

-5.4486228248429362e-18

In [12]:
y_std.mean()

1.3626846987180004e-16

In [13]:
# 標準化したデータで線形モデルを学習させる
lr_std = LinearRegression()
lr_std.fit(X_std, y_std)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
# 標準偏回帰係数を出力
coef_std = lr_std.coef_
coef_std

array([[ 0.03880077,  0.09652852,  0.04945043,  0.0582587 , -0.03287776,
        -0.08126186, -0.03000193,  0.16592898,  0.03432867,  0.01498169,
         0.01465268,  0.26172222,  0.01590189,  0.09228964,  0.00127784,
         0.06675092, -0.03314941,  0.16622224,  0.17396037,  0.04127993,
         0.09550094, -0.02567085,  0.03860375]])

In [19]:
sorted(coef_std[0], key=abs)

[0.0012778353872260478,
 0.014652676044582109,
 0.014981692667332748,
 0.015901885637110952,
 -0.02567085283395544,
 -0.030001931462340009,
 -0.032877755547506153,
 -0.033149412505637799,
 0.034328665253816726,
 0.038603749452754563,
 0.038800770126263977,
 0.041279929216399835,
 0.049450426204071085,
 0.058258699567617908,
 0.066750918109285268,
 -0.08126185585016947,
 0.092289641371650133,
 0.095500936205249298,
 0.09652851970289239,
 0.16592898004031201,
 0.16622224411984243,
 0.1739603704228177,
 0.26172222119607674]

In [24]:
#上位4つをpickしてもう一回重回帰
X_picked = df.loc[:,["GarageCars", "GrLivArea", "Neighborhood", 'OverallQual']]
# ホールド・アウト法によるデータの分割
# (X, y, テストにどの割合を割くか, 分割のしかたを決める乱数生成器)
# テストデータの割合は、test_size引数に指定することで変更可能です（今回は、train:test = 7:3）
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_picked, y, test_size = 0.3, random_state = 0)
# データ全体のサンプル数を確認
print(X_picked.shape)
print(y.shape)
# 重回帰の線形回帰を実行
from sklearn.linear_model import LinearRegression
lr_picked = LinearRegression()
# 重回帰線形モデルの学習
# trainデータのみを用いていることに注意
lr_picked.fit(X_train, y_train)

(1460, 4)
(1460, 1)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
# 偏回帰係数を出力
lr_picked.coef_

array([[ 15310.14423532,     52.76228411,   2970.11615461,  17268.37956976]])

In [26]:
# 自由度調整済み決定係数
# (決定係数, trainまたはtestのサンプル数, 利用した特徴量の数)
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score
# 自由度調整済み決定係数を出力
print('adjusted R^2')
print('train: %3f' % adjusted(lr_picked.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(lr_picked.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.791324
test : 0.760000


In [27]:
print('RMSE')
print('train: %.3f' % (mse(y_train, lr_picked.predict(X_train)) ** 1/2))
print('test : %.3f' % (mse(y_test, lr_picked.predict(X_test)) ** 1/2))

RMSE
train: 635190525.432
test : 810951501.720
